resolver: lts-10.1
packages:
- conduit/cereal-conduit
- conduit/conduit
- conduit/conduit-extra
- conduit/network-conduit-tls
- conduit/resourcet

- mono-traversable/minlen
- mono-traversable/mono-traversable
- mono-traversable/mono-traversable-instances
- mono-traversable/chunked-data
- mono-traversable/classy-prelude
- mono-traversable/classy-prelude-conduit
- mono-traversable/classy-prelude-yesod
- mono-traversable/conduit-combinators
- mono-traversable/mutable-containers

- stack/
- rio/

- yesod/yesod-core
- yesod/yesod-static
- yesod/yesod-persistent
- yesod/yesod-newsfeed
- yesod/yesod-form
- yesod/yesod-auth
- yesod/yesod-auth-oauth
- yesod/yesod-sitemap
- yesod/yesod-test
- yesod/yesod-bin
- yesod/yesod
- yesod/yesod-eventsource
# - yesod/yesod-websockets # streaming-commons 0.2

- xml/xml-conduit
- xml/xml-hamlet
- xml/html-conduit

- yaml

- wai/wai-extra
- wai/warp

- haskell-ide/project-template

- http-client/http-client
- http-client/http-conduit

- logger/monad-logger

- persistent/persistent
- persistent/persistent-template
- persistent/persistent-sqlite
- persistent/persistent-test
- persistent/persistent-mongoDB
- persistent/persistent-mysql
- persistent/persistent-postgresql

- typed-process
- pantry

- unliftio/unliftio-core
- unliftio/unliftio

- streaming-commons

flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
