resolver: lts-10.1
packages:
- conduit/cereal-conduit
- conduit/conduit
- conduit/conduit-extra
- conduit/network-conduit-tls
- conduit/resourcet

- mono-traversable/classy-prelude
- mono-traversable/classy-prelude-conduit
- mono-traversable/classy-prelude-yesod
- mono-traversable/conduit-combinators

- rio/

- yesod/yesod-core
- yesod/yesod-static
- yesod/yesod-persistent
- yesod/yesod-newsfeed
- yesod/yesod-form
- yesod/yesod-auth
- yesod/yesod-auth-oauth
- yesod/yesod-sitemap
- yesod/yesod-test
- yesod/yesod-bin
- yesod/yesod
- yesod/yesod-eventsource
- yesod/yesod-websockets

- xml/xml-conduit
- xml/html-conduit

- persistent/persistent
- persistent/persistent-sqlite
- persistent/persistent-mongoDB
- persistent/persistent-mysql
- persistent/persistent-postgresql

#- pantry

flags:
  stack:
    hide-dependency-versions: true
    supported-build: true

extra-deps:
- project-template-0.2.0.1
- typed-process-0.2.1.0
- unliftio-0.2.4.0
- unliftio-core-0.1.1.0
- monad-logger-0.3.28
- yaml-0.8.27
- mono-traversable-1.0.8.0
- wai-extra-3.0.22.0
- http-conduit-2.3.0
